# filename -- frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-project-frontend
  labels:
    app: 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-project-frontend
  template:
    metadata:
      labels:
        app: java-project-frontend
    spec:
      containers:
      - name: java-project-final
        image: iamsumitkumar/java-project-frontend:24
        ports:
        - containerPort: 3000
